title: Georgiana Gligor
subtitle: Large-scale Software Architect. PhD student.

author: Georgiana Gligor
description: Online Curriculum Vitae of Georgiana Gligor

cover:
  oneliner: Geek. Mother. Do-er.
  lead: >
    Application architect that enjoys crafting efficient large-scale solutions.

  details:
    - After using PHP for more than a decade, I'm a living proof that geek girls are an asset to any team. I love taming the Force of the DevOps dark side and mentoring team mates in achieving craftsmanship.
    - Over the past year I dived deep into Artificial Intelligence, using Watson and Rainbird to deliver real-life applications. This also led me into starting a PhD in Systems Engineering.

social:
  skype: georgiana.beju
  facebook: gbtekkie
  linkedin: gbtekkie
  mail: gb@tekkie.ro

experience:
  phd:
    company: Technical University of Cluj-Napoca
    position: PhD Student
    since: October 2016
    location: Cluj-Napoca, Romania
    details:
      - Systems Engineering
      - Artificial Intelligence

  tekkie:
    company: Tekkie Consulting
    position: CTO / Owner
    since: August 2011
    location: Alba Iulia, Romania
    details:
      - Large-scale application architecture consultancy.
      - Artificial intelligence products using Watson and Rainbird.

  lola:
    company: Lola Enterprises
    position: Principal Developer
    since: October 2011
    until: April 2015
    location: Cluj-Napoca, Romania
    details:
      - Kickstarted offshore development technical team focused on developing complex SOA applications with a strong emphasis on performance, both application- and component-level.
      - Prepared technical architecture of SOA layers, using a LAMP stack backbone.
      - Mentor developer colleagues to best practices (TDD, continuous integration, BDD, etc).
      - Design and implement data migration and massaging processes, aimed at large amounts of data.
      - Ensured smooth integration between backend, frontend and administration components.
      - Developed backend components.
      - Occasionally wearing the scrum master hat.

  easytobook:
    company: Easy To Book GmbH
    position: Senior Application Developer
    since: November 2009
    until: November 2011
    location: Amsterdam, Netherlands
    details:
      - Design and implement multi-tiered applications aimed at allowing people to book hotel rooms from multiple sources.
      - Optimise performance of public reservations engine.
      - Design and develop analytics solutions for the marketing team.
      - Design and develop other internal company applications.

  geoweb:
    company: GeoWeb Consulting
    position: LAMP Contractor, co-owner
    since: August 2009
    until: December 2010
    location: London, United Kingdom
    details:
      - Design and develop backend applications for various UK customers.
      - Develop websites using LAMP stack.
      - Advise strategies to stabilise and improve legacy codebases.

  pfa:
    company: Beju Georgiana-Ioana PFA
    position: LAMP contractor
    location: Timisoara, Romania
    since: January 2009
    until: July 2009
    details:
      - Implemented a real estate framework which consumes a SOAP API from www.imobiliare.ro to obtain real estate properties and display them in the company’s own website (www.m-imobiliare.ro; www.mix-imobiliare.ro)
      - PHP, Javascript, HTML, CSS web development

  imobiliare:
    company: Realmedia Network SRL
    position: Lead Developer
    location: Timisoara, Romania
    since: May 2006
    until: December 2009
    details:
      - Coordinated the technical team for the online software development department.
      - Established the entire software development process, chose the software tools, decided workflow and responsibilities of team members.
      - Architected and documented the base framework for development, chose libraries and other development tools, designed structures and code for the individual projects.
      - Redesigned the entire code base for the new generation of real estate online software provided by imobiliare.ro

  ciao:
    company: Ciao GmbH
    position: Developer
    since: December 2004
    until: May 2006
    location: Timisoara, Romania
    details:
      - Develop data migration scripts for extremely large amounts of data. Handled the E and T part of a custom ETL solution.
      - Optimise database access and data extraction, in particular MySQL and Postgresql.
      - Develop command-line scripts for background tasks.
      - Develop internal back-office solution.

  iqsolutions:
    company: IQ Solutions
    position: Web Developer
    location: Cluj-Napoca, Romania
    since: November 2003
    until: December 2004
    details:
      - Develop an employee management and time tracking solution using LAMP stack.
      - Develop company website.
      - Elaborate user manuals for the company products.
      - Develop an inventory management product using MS Access.

references:
  lola:
    -
      name: Luke McNeice
      position: CEO
      referenced_at: May 17, 2015
      role: Direct manager
      details: >
        Georgiana is an incredibly talented technical evangelist who was one of our founding brains at Cloud Troopers. She has the deft hand of an experienced technologist coupled with an undying drive to hit a deadline. Cou- pled with ubër coding skills, Georgiana has somewhat of a unique skill for geeks in actually understanding why you’re building something.
    -
      name: Florin Besleaga
      position: DevOps Engineer
      referenced_at: Apr 23, 2015
      role: Worked directly
      details: >
        As a Sys-Admin / DevOPS, one requires from his developer colleagues the ability to formulate a correct request, understand what the project and release flow is all about, understanding that timing is of the es- sence and knowing the best way to develop the code according to the available infrastructure resources. Not only that Georgiana met all the above, but she, as a tech lead, made sure that all the developers in her team were up to the desired standards and profes- sionalism, and provided extremely valuable insight on the research and development side for all the teams she had contact with. She is, indeed, one of the best developers i worked with, extremely dedicated to her work and to the projects she managed.
    -
      name: Harry Harold
      position: User experience designer. Product manager.
      referenced_at: Apr 2, 2015
      role: Worked directly
      details: >
        Georgiana does not stop until a product is delivered successfully.
        You’ll find her understanding the entire architecture and how the solution works
        as well as delivering her personal coding workload and mentoring junior colleagues.
        I’ve worked with her twice, I asked to work with her the second time,
        and I look forward to working with her again.
    -
      name: Bryan Lord
      position: Founder & CEO.
      referenced_at: Feb 21, 2015
      role: Customer
      details: >
        I’ve been working with Georgiana over the past 1.5 years building our software company. Her technical ex- pertise, attention to detail combined with her approach make her an extremely valuable resource. She’s been readily available and very proactive throughout the development process and is a pleasure to work with.
    -
      name: Amoor Avakian
      position: FProduct Owner.
      referenced_at: Oct 17, 2011
      role: Direct manager
      details: >
        Get it done right the first time. The best motto I believe that Georgiana lives and works by. The path to do it may be hard, take tough discussions that might not always go smoothly but you know that you will get a solution that works, it will be coded well and will have inherent business smarts right into it. Georgiana is an ethical and valuable person and can carry the project to success.
    -
      name: Wouter Blok
      position: CMO.
      referenced_at: Sep 26, 2011
      role: Customer
      details: >
        This girl is able to code my marketing ideas, how cool is that? She loves to close the gap between marketing and development, which is a powerful combination. I enjoy her quirkiness, smart talk and occasional back rub. ;)
    -
      name: Gigi Picazio
      position: Marketing.
      referenced_at: Sep 20, 2011
      role: Colleague
      details: >
        I’ve been working with Georgiana for almost 2 years at Easytobook.com. I’m working at marketing department, Georgiana at R&D department and, despite all the commonplaces about the relationship between marketeers and developers, Georgiana is the kind of developer that can make a marketeer happy. She’s always helpful and offers her technical knowledge to solve problems keeping always an eye on the priorities. As a colleague, I know that Georgiana is someone I can always count on.
    -
      name: Lucian Daniliuc
      position: PHP developer.
      referenced_at: Apr 15, 2011
      role: Coordinated by Georgiana
      details: >
        Georgiana is a practical business-oriented developer that exceeds in clean coding, code optimization and reusability, algorithm abstraction, application and da- tabase design.
    -
      name: Christian Kählig
      position: Project manager.
      referenced_at: Oct 11, 2008
      role: Direct manager
      details: >
        Georgiana worked for me in the context of our largest project at that time where we redesigned the search component of the comparison shopping portal. She is very eager to learn and motivated to go the extra mile. With her driven nature and technological background combined with a good sense for people handling, I would definitely recommend her for technical team leadership roles or as change agent in larger projects. It was always fun to work with her and I really enjoyed the time in romania where she and many other friendly and motivated developers work located.
    -
      name: Christopher Scollo
      position: CTO.
      referenced_at: Feb 24, 2008
      role: Direct manager
      details: >
        Georgiana is a talented technologist who approaches her work with care and diligence.
