references:
  lola:
    -
      name: Luke McNeice
      position: CEO
      referenced_at: May 17, 2015
      role: Direct manager
      details: >
        Georgiana is an incredibly talented technical evangelist who was one of our founding brains at Cloud Troopers. She has the deft hand of an experienced technologist coupled with an undying drive to hit a deadline. Cou- pled with ubër coding skills, Georgiana has somewhat of a unique skill for geeks in actually understanding why you’re building something.
    -
      name: Florin Besleaga
      position: DevOps Engineer
      referenced_at: Apr 23, 2015
      role: Worked directly
      details: >
        As a Sys-Admin / DevOPS, one requires from his developer colleagues the ability to formulate a correct request, understand what the project and release flow is all about, understanding that timing is of the es- sence and knowing the best way to develop the code according to the available infrastructure resources. Not only that Georgiana met all the above, but she, as a tech lead, made sure that all the developers in her team were up to the desired standards and profes- sionalism, and provided extremely valuable insight on the research and development side for all the teams she had contact with. She is, indeed, one of the best developers i worked with, extremely dedicated to her work and to the projects she managed.
    -
      name: Harry Harold
      position: User experience designer. Product manager.
      referenced_at: Apr 2, 2015
      role: Worked directly
      details: >
        Georgiana does not stop until a product is delivered successfully.
        You’ll find her understanding the entire architecture and how the solution works
        as well as delivering her personal coding workload and mentoring junior colleagues.
        I’ve worked with her twice, I asked to work with her the second time,
        and I look forward to working with her again.
    -
      name: Bryan Lord
      position: Founder & CEO.
      referenced_at: Feb 21, 2015
      role: Customer
      details: >
        I’ve been working with Georgiana over the past 1.5 years building our software company. Her technical ex- pertise, attention to detail combined with her approach make her an extremely valuable resource. She’s been readily available and very proactive throughout the development process and is a pleasure to work with.
    -
      name: Amoor Avakian
      position: FProduct Owner.
      referenced_at: Oct 17, 2011
      role: Direct manager
      details: >
        Get it done right the first time. The best motto I believe that Georgiana lives and works by. The path to do it may be hard, take tough discussions that might not always go smoothly but you know that you will get a solution that works, it will be coded well and will have inherent business smarts right into it. Georgiana is an ethical and valuable person and can carry the project to success.
    -
      name: Wouter Blok
      position: CMO.
      referenced_at: Sep 26, 2011
      role: Customer
      details: >
        This girl is able to code my marketing ideas, how cool is that? She loves to close the gap between marketing and development, which is a powerful combination. I enjoy her quirkiness, smart talk and occasional back rub. ;)
    -
      name: Gigi Picazio
      position: Marketing.
      referenced_at: Sep 20, 2011
      role: Colleague
      details: >
        I’ve been working with Georgiana for almost 2 years at Easytobook.com. I’m working at marketing department, Georgiana at R&D department and, despite all the commonplaces about the relationship between marketeers and developers, Georgiana is the kind of developer that can make a marketeer happy. She’s always helpful and offers her technical knowledge to solve problems keeping always an eye on the priorities. As a colleague, I know that Georgiana is someone I can always count on.
    -
      name: Lucian Daniliuc
      position: PHP developer.
      referenced_at: Apr 15, 2011
      role: Coordinated by Georgiana
      details: >
        Georgiana is a practical business-oriented developer that exceeds in clean coding, code optimization and reusability, algorithm abstraction, application and da- tabase design.
    -
      name: Christian Kählig
      position: Project manager.
      referenced_at: Oct 11, 2008
      role: Direct manager
      details: >
        Georgiana worked for me in the context of our largest project at that time where we redesigned the search component of the comparison shopping portal. She is very eager to learn and motivated to go the extra mile. With her driven nature and technological background combined with a good sense for people handling, I would definitely recommend her for technical team leadership roles or as change agent in larger projects. It was always fun to work with her and I really enjoyed the time in romania where she and many other friendly and motivated developers work located.
    -
      name: Christopher Scollo
      position: CTO.
      referenced_at: Feb 24, 2008
      role: Direct manager
      details: >
        Georgiana is a talented technologist who approaches her work with care and diligence.
